BEGIN;

CREATE TABLE IF NOT EXISTS automation_execution_step_results (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_task_id integer NOT NULL REFERENCES automation_execution_tasks(id) ON DELETE CASCADE,
    step_no integer NOT NULL,
    name varchar(300) NOT NULL,
    status varchar(16) NOT NULL,
    method varchar(10) NOT NULL,
    path varchar(2000) NOT NULL,
    status_code integer,
    duration_ms integer,
    request_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    assertions jsonb NOT NULL DEFAULT '[]'::jsonb,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_automation_execution_step_results_status
        CHECK (status IN ('PASSED','FAILED','SKIPPED')),
    CONSTRAINT chk_automation_execution_step_results_step_no CHECK (step_no > 0),
    CONSTRAINT chk_automation_step_duration CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT uq_automation_execution_step_task_no UNIQUE (execution_task_id, step_no)
);

CREATE INDEX IF NOT EXISTS ix_automation_execution_step_results_task
    ON automation_execution_step_results(execution_task_id, step_no);

COMMENT ON TABLE automation_execution_step_results IS '自动化执行任务的逐步骤脱敏结果';
COMMENT ON COLUMN automation_execution_step_results.execution_task_id IS '所属自动化执行任务 ID';
COMMENT ON COLUMN automation_execution_step_results.step_no IS '步骤顺序号，从 1 开始';
COMMENT ON COLUMN automation_execution_step_results.name IS '执行时的步骤名称快照';
COMMENT ON COLUMN automation_execution_step_results.status IS 'PASSED/FAILED/SKIPPED';
COMMENT ON COLUMN automation_execution_step_results.method IS 'HTTP 方法';
COMMENT ON COLUMN automation_execution_step_results.path IS '不包含主机的相对请求路径';
COMMENT ON COLUMN automation_execution_step_results.status_code IS 'HTTP 响应状态码';
COMMENT ON COLUMN automation_execution_step_results.duration_ms IS '步骤耗时毫秒数';
COMMENT ON COLUMN automation_execution_step_results.request_summary IS '请求结构摘要，不保存请求值或凭据';
COMMENT ON COLUMN automation_execution_step_results.response_summary IS '响应摘要，不保存响应正文';
COMMENT ON COLUMN automation_execution_step_results.assertions IS '断言类型、表达式和通过状态';
COMMENT ON COLUMN automation_execution_step_results.error_message IS '步骤失败的脱敏原因';

COMMIT;
