BEGIN;

ALTER TABLE test_environments
    ADD COLUMN IF NOT EXISTS environment_type varchar(20) NOT NULL DEFAULT 'TEST';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_test_environments_type'
          AND conrelid = 'test_environments'::regclass
    ) THEN
        ALTER TABLE test_environments ADD CONSTRAINT chk_test_environments_type
            CHECK (environment_type IN ('LOCAL','DEVELOPMENT','TEST','STAGING','PRODUCTION'));
    END IF;
END $$;

COMMENT ON COLUMN test_environments.environment_type IS '环境用途；PRODUCTION 禁止自动化执行';

CREATE TABLE IF NOT EXISTS automation_execution_tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer NOT NULL REFERENCES test_projects(id) ON DELETE CASCADE,
    definition_id integer NOT NULL REFERENCES automation_definitions(id) ON DELETE RESTRICT,
    environment_id integer NOT NULL REFERENCES test_environments(id) ON DELETE RESTRICT,
    status varchar(24) NOT NULL DEFAULT 'PENDING',
    progress integer NOT NULL DEFAULT 0,
    current_stage varchar(80) NOT NULL DEFAULT 'QUEUED',
    timeout_seconds integer NOT NULL,
    celery_task_id varchar(80),
    definition_hash varchar(64) NOT NULL,
    environment_updated_at timestamptz NOT NULL,
    result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_message text,
    requested_by integer REFERENCES users(id) ON DELETE SET NULL,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_automation_execution_tasks_status CHECK (
        status IN ('PENDING','RUNNING','CANCEL_REQUESTED','PASSED','FAILED','TIMED_OUT','CANCELLED')
    ),
    CONSTRAINT chk_automation_execution_tasks_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT chk_automation_execution_tasks_timeout CHECK (timeout_seconds BETWEEN 10 AND 7200)
);

CREATE INDEX IF NOT EXISTS ix_automation_execution_tasks_project_status
    ON automation_execution_tasks(project_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_automation_execution_tasks_active_definition
    ON automation_execution_tasks(definition_id)
    WHERE status IN ('PENDING','RUNNING','CANCEL_REQUESTED');

COMMENT ON TABLE automation_execution_tasks IS '受控接口自动化后台执行任务';
COMMENT ON COLUMN automation_execution_tasks.id IS '执行任务主键';
COMMENT ON COLUMN automation_execution_tasks.project_id IS '所属项目 ID';
COMMENT ON COLUMN automation_execution_tasks.definition_id IS '执行的已审批定义 ID';
COMMENT ON COLUMN automation_execution_tasks.environment_id IS '目标测试环境 ID';
COMMENT ON COLUMN automation_execution_tasks.status IS '任务执行状态';
COMMENT ON COLUMN automation_execution_tasks.progress IS '任务进度百分比';
COMMENT ON COLUMN automation_execution_tasks.current_stage IS '当前执行阶段';
COMMENT ON COLUMN automation_execution_tasks.timeout_seconds IS '整次任务总超时秒数';
COMMENT ON COLUMN automation_execution_tasks.celery_task_id IS 'Celery Broker 任务 ID';
COMMENT ON COLUMN automation_execution_tasks.definition_hash IS '提交时自动化定义内容摘要';
COMMENT ON COLUMN automation_execution_tasks.environment_updated_at IS '提交时测试环境更新时间，用于阻止配置漂移';
COMMENT ON COLUMN automation_execution_tasks.result_summary IS '最小执行结论；详细步骤报告由 FR-AUTO-003 扩展';
COMMENT ON COLUMN automation_execution_tasks.error_message IS '失败时的脱敏错误摘要';
COMMENT ON COLUMN automation_execution_tasks.requested_by IS '发起任务的用户 ID';
COMMENT ON COLUMN automation_execution_tasks.started_at IS '开始执行时间';
COMMENT ON COLUMN automation_execution_tasks.finished_at IS '进入最终状态时间';
COMMENT ON COLUMN automation_execution_tasks.created_at IS '创建时间';
COMMENT ON COLUMN automation_execution_tasks.updated_at IS '更新时间';

COMMIT;
