BEGIN;

CREATE TABLE IF NOT EXISTS automation_definitions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer NOT NULL REFERENCES test_projects(id) ON DELETE CASCADE,
    test_case_id integer NOT NULL REFERENCES test_cases(id) ON DELETE CASCADE,
    name varchar(300) NOT NULL,
    version integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    schema_version varchar(20) NOT NULL DEFAULT '1.0',
    source_case_version integer NOT NULL,
    definition jsonb NOT NULL,
    definition_hash varchar(64) NOT NULL,
    created_by integer REFERENCES users(id) ON DELETE SET NULL,
    approved_by integer REFERENCES users(id) ON DELETE SET NULL,
    approved_at timestamptz,
    retired_at timestamptz,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_automation_definitions_case_version UNIQUE (test_case_id, version),
    CONSTRAINT chk_automation_definitions_version CHECK (version > 0),
    CONSTRAINT chk_automation_definitions_status CHECK (status IN ('DRAFT', 'APPROVED', 'RETIRED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_automation_definitions_approved_case
    ON automation_definitions(test_case_id)
    WHERE status = 'APPROVED' AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_automation_definitions_project_status
    ON automation_definitions(project_id, status);

COMMENT ON TABLE automation_definitions IS '受控 JSON 接口自动化定义及其审批版本';
COMMENT ON COLUMN automation_definitions.id IS '自动化定义主键';
COMMENT ON COLUMN automation_definitions.project_id IS '所属测试项目 ID，用于项目数据权限隔离';
COMMENT ON COLUMN automation_definitions.test_case_id IS '来源测试用例 ID';
COMMENT ON COLUMN automation_definitions.name IS '自动化定义名称';
COMMENT ON COLUMN automation_definitions.version IS '同一用例下递增的定义版本';
COMMENT ON COLUMN automation_definitions.status IS '定义状态：DRAFT 草稿、APPROVED 已审批、RETIRED 已退出使用';
COMMENT ON COLUMN automation_definitions.schema_version IS '受控 JSON 协议版本';
COMMENT ON COLUMN automation_definitions.source_case_version IS '生成定义时来源测试用例的版本快照';
COMMENT ON COLUMN automation_definitions.definition IS '已通过白名单校验的自动化步骤 JSON';
COMMENT ON COLUMN automation_definitions.definition_hash IS '规范化 JSON 的 SHA-256 摘要';
COMMENT ON COLUMN automation_definitions.created_by IS '创建定义的用户 ID';
COMMENT ON COLUMN automation_definitions.approved_by IS '审批该版本的用户 ID';
COMMENT ON COLUMN automation_definitions.approved_at IS '定义通过审批的时间';
COMMENT ON COLUMN automation_definitions.retired_at IS '定义退出使用的时间';
COMMENT ON COLUMN automation_definitions.deleted_at IS '软删除时间；为空表示仍有效';
COMMENT ON COLUMN automation_definitions.created_at IS '创建时间';
COMMENT ON COLUMN automation_definitions.updated_at IS '更新时间';

COMMIT;
