/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'ai',
    path: '/ai',
    component: 'layout.base',
    meta: {
      title: 'ai',
      i18nKey: 'route.ai'
    },
    children: [
      {
        name: 'ai_mcp',
        path: '/ai/mcp',
        component: 'view.ai_mcp',
        meta: {
          title: 'ai_mcp',
          i18nKey: 'route.ai_mcp',
          icon: 'mdi:connection',
          order: 6
        }
      },
      {
        name: 'ai_model',
        path: '/ai/model',
        component: 'view.ai_model',
        meta: {
          title: 'ai_model',
          i18nKey: 'route.ai_model'
        }
      },
      {
        name: 'ai_notification',
        path: '/ai/notification',
        component: 'view.ai_notification',
        meta: {
          title: 'ai_notification',
          i18nKey: 'route.ai_notification'
        }
      },
      {
        name: 'ai_prompt',
        path: '/ai/prompt',
        component: 'view.ai_prompt',
        meta: {
          title: 'ai_prompt',
          i18nKey: 'route.ai_prompt'
        }
      },
      {
        name: 'ai_provider',
        path: '/ai/provider',
        component: 'view.ai_provider',
        meta: {
          title: 'ai_provider',
          i18nKey: 'route.ai_provider'
        }
      },
      {
        name: 'ai_usage',
        path: '/ai/usage',
        component: 'view.ai_usage',
        meta: {
          title: 'ai_usage',
          i18nKey: 'route.ai_usage'
        }
      }
    ]
  },
  {
    name: 'alova',
    path: '/alova',
    component: 'layout.base',
    meta: {
      title: 'alova',
      i18nKey: 'route.alova',
      icon: 'carbon:http',
      order: 7
    },
    children: [
      {
        name: 'alova_request',
        path: '/alova/request',
        component: 'view.alova_request',
        meta: {
          title: 'alova_request',
          i18nKey: 'route.alova_request',
          order: 1
        }
      },
      {
        name: 'alova_scenes',
        path: '/alova/scenes',
        component: 'view.alova_scenes',
        meta: {
          title: 'alova_scenes',
          i18nKey: 'route.alova_scenes',
          icon: 'cbi:scene-dynamic',
          order: 3
        }
      },
      {
        name: 'alova_user',
        path: '/alova/user',
        component: 'view.alova_user',
        meta: {
          title: 'alova_user',
          i18nKey: 'route.alova_user',
          icon: 'carbon:user-multiple',
          order: 2
        }
      }
    ]
  },
  {
    name: 'automation',
    path: '/automation',
    component: 'layout.base',
    meta: {
      title: 'automation',
      i18nKey: 'route.automation',
      icon: 'mdi:robot-industrial-outline',
      order: 4
    },
    children: [
      {
        name: 'automation_definitions',
        path: '/automation/definitions',
        component: 'view.automation_definitions',
        meta: {
          title: 'automation_definitions',
          i18nKey: 'route.automation_definitions',
          icon: 'mdi:file-code-outline',
          order: 1
        }
      },
      {
        name: 'automation_schedules',
        path: '/automation/schedules',
        component: 'view.automation_schedules',
        meta: {
          title: 'automation_schedules',
          i18nKey: 'route.automation_schedules'
        }
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 6
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off',
          order: 2
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request',
          icon: 'carbon:network-overlay',
          order: 3
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page',
          icon: 'ic:round-supervisor-account',
          order: 5,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab',
          order: 1
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth',
          icon: 'ic:round-construction',
          order: 4
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base',
    meta: {
      title: 'knowledge',
      i18nKey: 'route.knowledge',
      icon: 'mdi:bookshelf',
      order: 2
    },
    children: [
      {
        name: 'knowledge_bases',
        path: '/knowledge/bases',
        component: 'view.knowledge_bases',
        meta: {
          title: 'knowledge_bases',
          i18nKey: 'route.knowledge_bases',
          icon: 'mdi:database-outline',
          order: 1
        }
      },
      {
        name: 'knowledge_chat',
        path: '/knowledge/chat',
        component: 'view.knowledge_chat',
        meta: {
          title: 'knowledge_chat',
          i18nKey: 'route.knowledge_chat'
        }
      },
      {
        name: 'knowledge_documents',
        path: '/knowledge/documents',
        component: 'view.knowledge_documents',
        meta: {
          title: 'knowledge_documents',
          i18nKey: 'route.knowledge_documents',
          icon: 'mdi:file-document-multiple-outline',
          order: 2
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      order: 8
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          order: 1
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          order: 2
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'plugin',
    path: '/plugin',
    component: 'layout.base',
    meta: {
      title: '插件示例',
      i18nKey: 'route.plugin',
      order: 7,
      icon: 'clarity:plugin-line'
    },
    children: [
      {
        name: 'plugin_barcode',
        path: '/plugin/barcode',
        component: 'view.plugin_barcode',
        meta: {
          title: 'plugin_barcode',
          i18nKey: 'route.plugin_barcode',
          icon: 'ic:round-barcode'
        }
      },
      {
        name: 'plugin_charts',
        path: '/plugin/charts',
        meta: {
          title: 'plugin_charts',
          i18nKey: 'route.plugin_charts',
          icon: 'mdi:chart-areaspline'
        },
        children: [
          {
            name: 'plugin_charts_antv',
            path: '/plugin/charts/antv',
            component: 'view.plugin_charts_antv',
            meta: {
              title: 'plugin_charts_antv',
              i18nKey: 'route.plugin_charts_antv',
              icon: 'hugeicons:flow-square'
            }
          },
          {
            name: 'plugin_charts_echarts',
            path: '/plugin/charts/echarts',
            component: 'view.plugin_charts_echarts',
            meta: {
              title: 'plugin_charts_echarts',
              i18nKey: 'route.plugin_charts_echarts',
              icon: 'simple-icons:apacheecharts'
            }
          },
          {
            name: 'plugin_charts_vchart',
            path: '/plugin/charts/vchart',
            component: 'view.plugin_charts_vchart',
            meta: {
              title: 'plugin_charts_vchart',
              i18nKey: 'route.plugin_charts_vchart',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_copy',
        path: '/plugin/copy',
        component: 'view.plugin_copy',
        meta: {
          title: 'plugin_copy',
          i18nKey: 'route.plugin_copy',
          icon: 'mdi:clipboard-outline'
        }
      },
      {
        name: 'plugin_editor',
        path: '/plugin/editor',
        meta: {
          title: 'plugin_editor',
          i18nKey: 'route.plugin_editor',
          icon: 'icon-park-outline:editor'
        },
        children: [
          {
            name: 'plugin_editor_markdown',
            path: '/plugin/editor/markdown',
            component: 'view.plugin_editor_markdown',
            meta: {
              title: 'plugin_editor_markdown',
              i18nKey: 'route.plugin_editor_markdown',
              icon: 'ri:markdown-line'
            }
          },
          {
            name: 'plugin_editor_quill',
            path: '/plugin/editor/quill',
            component: 'view.plugin_editor_quill',
            meta: {
              title: 'plugin_editor_quill',
              i18nKey: 'route.plugin_editor_quill',
              icon: 'mdi:file-document-edit-outline'
            }
          }
        ]
      },
      {
        name: 'plugin_excel',
        path: '/plugin/excel',
        component: 'view.plugin_excel',
        meta: {
          title: 'plugin_excel',
          i18nKey: 'route.plugin_excel',
          icon: 'ri:file-excel-2-line',
          keepAlive: true
        }
      },
      {
        name: 'plugin_gantt',
        path: '/plugin/gantt',
        meta: {
          title: 'plugin_gantt',
          i18nKey: 'route.plugin_gantt',
          icon: 'ant-design:bar-chart-outlined'
        },
        children: [
          {
            name: 'plugin_gantt_dhtmlx',
            path: '/plugin/gantt/dhtmlx',
            component: 'view.plugin_gantt_dhtmlx',
            meta: {
              title: 'plugin_gantt_dhtmlx',
              i18nKey: 'route.plugin_gantt_dhtmlx',
              icon: 'gridicons:posts'
            }
          },
          {
            name: 'plugin_gantt_vtable',
            path: '/plugin/gantt/vtable',
            component: 'view.plugin_gantt_vtable',
            meta: {
              title: 'plugin_gantt_vtable',
              i18nKey: 'route.plugin_gantt_vtable',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_icon',
        path: '/plugin/icon',
        component: 'view.plugin_icon',
        meta: {
          title: 'plugin_icon',
          i18nKey: 'route.plugin_icon',
          localIcon: 'custom-icon'
        }
      },
      {
        name: 'plugin_map',
        path: '/plugin/map',
        component: 'view.plugin_map',
        meta: {
          title: 'plugin_map',
          i18nKey: 'route.plugin_map',
          icon: 'mdi:map'
        }
      },
      {
        name: 'plugin_pdf',
        path: '/plugin/pdf',
        component: 'view.plugin_pdf',
        meta: {
          title: 'plugin_pdf',
          i18nKey: 'route.plugin_pdf',
          icon: 'uiw:file-pdf'
        }
      },
      {
        name: 'plugin_pinyin',
        path: '/plugin/pinyin',
        component: 'view.plugin_pinyin',
        meta: {
          title: 'plugin_pinyin',
          i18nKey: 'route.plugin_pinyin',
          icon: 'entypo-social:google-hangouts'
        }
      },
      {
        name: 'plugin_print',
        path: '/plugin/print',
        component: 'view.plugin_print',
        meta: {
          title: 'plugin_print',
          i18nKey: 'route.plugin_print',
          icon: 'mdi:printer'
        }
      },
      {
        name: 'plugin_swiper',
        path: '/plugin/swiper',
        component: 'view.plugin_swiper',
        meta: {
          title: 'plugin_swiper',
          i18nKey: 'route.plugin_swiper',
          icon: 'simple-icons:swiper'
        }
      },
      {
        name: 'plugin_tables',
        path: '/plugin/tables',
        meta: {
          title: 'plugin_tables',
          i18nKey: 'route.plugin_tables',
          icon: 'icon-park-outline:table'
        },
        children: [
          {
            name: 'plugin_tables_vtable',
            path: '/plugin/tables/vtable',
            component: 'view.plugin_tables_vtable',
            meta: {
              title: 'plugin_tables_vtable',
              i18nKey: 'route.plugin_tables_vtable',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_typeit',
        path: '/plugin/typeit',
        component: 'view.plugin_typeit',
        meta: {
          title: 'plugin_typeit',
          i18nKey: 'route.plugin_typeit',
          icon: 'mdi:typewriter'
        }
      },
      {
        name: 'plugin_video',
        path: '/plugin/video',
        component: 'view.plugin_video',
        meta: {
          title: 'plugin_video',
          i18nKey: 'route.plugin_video',
          icon: 'mdi:video'
        }
      }
    ]
  },
  {
    name: 'project',
    path: '/project',
    component: 'layout.base',
    meta: {
      title: 'project',
      i18nKey: 'route.project'
    },
    children: [
      {
        name: 'project_environments',
        path: '/project/environments',
        component: 'view.project_environments',
        meta: {
          title: 'project_environments',
          i18nKey: 'route.project_environments'
        }
      },
      {
        name: 'project_info',
        path: '/project/info',
        component: 'view.project_info',
        meta: {
          title: 'project_info',
          i18nKey: 'route.project_info'
        }
      },
      {
        name: 'project_members',
        path: '/project/members',
        component: 'view.project_members',
        meta: {
          title: 'project_members',
          i18nKey: 'route.project_members'
        }
      },
      {
        name: 'project_modules',
        path: '/project/modules',
        component: 'view.project_modules',
        meta: {
          title: 'project_modules',
          i18nKey: 'route.project_modules'
        }
      }
    ]
  },
  {
    name: 'requirement',
    path: '/requirement',
    component: 'layout.base',
    meta: {
      title: 'requirement',
      i18nKey: 'route.requirement',
      icon: 'mdi:clipboard-text-search-outline',
      order: 3
    },
    children: [
      {
        name: 'requirement_coverage',
        path: '/requirement/coverage',
        component: 'view.requirement_coverage',
        meta: {
          title: 'requirement_coverage',
          i18nKey: 'route.requirement_coverage',
          icon: 'mdi:table-search',
          order: 2
        }
      },
      {
        name: 'requirement_detail',
        path: '/requirement/detail',
        component: 'view.requirement_detail',
        meta: {
          title: 'requirement_detail',
          i18nKey: 'route.requirement_detail',
          hideInMenu: true,
          activeMenu: 'requirement_requirements'
        }
      },
      {
        name: 'requirement_requirements',
        path: '/requirement/requirements',
        component: 'view.requirement_requirements',
        meta: {
          title: 'requirement_requirements',
          i18nKey: 'route.requirement_requirements',
          icon: 'mdi:file-document-edit-outline',
          order: 1
        }
      },
      {
        name: 'requirement_review',
        path: '/requirement/review',
        component: 'view.requirement_review',
        meta: {
          title: 'requirement_review',
          i18nKey: 'route.requirement_review',
          icon: 'mdi:clipboard-check-multiple-outline',
          order: 4
        }
      },
      {
        name: 'requirement_supervisor',
        path: '/requirement/supervisor',
        component: 'view.requirement_supervisor',
        meta: {
          title: 'requirement_supervisor',
          i18nKey: 'route.requirement_supervisor'
        }
      },
      {
        name: 'requirement_test-cases',
        path: '/requirement/test-cases',
        component: 'view.requirement_test-cases',
        meta: {
          title: 'requirement_test-cases',
          i18nKey: 'route.requirement_test-cases',
          icon: 'mdi:clipboard-list-outline',
          order: 3
        }
      }
    ]
  },
  {
    name: 'tools',
    path: '/tools',
    component: 'layout.base',
    meta: {
      title: 'tools',
      i18nKey: 'route.tools'
    },
    children: [
      {
        name: 'tools_center',
        path: '/tools/center',
        component: 'view.tools_center',
        meta: {
          title: 'tools_center',
          i18nKey: 'route.tools_center'
        }
      },
      {
        name: 'tools_connections',
        path: '/tools/connections',
        component: 'view.tools_connections',
        meta: {
          title: 'tools_connections',
          i18nKey: 'route.tools_connections'
        }
      },
      {
        name: 'tools_file-templates',
        path: '/tools/file-templates',
        component: 'view.tools_file-templates',
        meta: {
          title: 'tools_file-templates',
          i18nKey: 'route.tools_file-templates'
        }
      },
      {
        name: 'tools_tasks',
        path: '/tools/tasks',
        component: 'view.tools_tasks',
        meta: {
          title: 'tools_tasks',
          i18nKey: 'route.tools_tasks'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
